# Generated by Django 4.2.25 on 2026-02-22 23:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_recipefavorite_recipes_recipefavorite_unique_user_and_favourite_recipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Количество должно быть больше 0'), django.core.validators.MaxValueValidator(1000, message='Количество должно быть от 1 до 10000')], verbose_name='Количество'),
        ),
    ]
