# Generated by Django 4.2.25 on 2026-02-24 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipeingredient_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Время приготовления не может быть меньше 1'), django.core.validators.MaxValueValidator(32767, message='Время приготовления должно быть от 1 до 32767 минут')], verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Количество должно быть больше 0'), django.core.validators.MaxValueValidator(32767, message='Количество должно быть от 1 до 32767')], verbose_name='Количество'),
        ),
    ]
