# Generated by Django 4.2.25 on 2025-11-14 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_follow_follow_users_follow_unique_following_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='user_being_followed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
