# Generated by Django 4.2.25 on 2025-11-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_follow_user_being_followed'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='users_follow_prevent_self_follow',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('user_is_following', models.F('user_being_followed')), _negated=True), name='users_follow_prevent_self_follow'),
        ),
    ]
