# Generated by Django 4.2.25 on 2025-11-15 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_prevent_username_me'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='prevent_username_me',
        ),
    ]
