# Generated by Django 4.2.25 on 2026-02-20 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='user_is_following',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='user_being_followed',
            new_name='author',
        ),
    ]
